services:
  rabbitmq:
    container_name: booking-rabbitmq-1
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # Management plugin port
  postgresql:
    container_name: booking-postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: booking 
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: